-- MySQL Script generated by MySQL Workbench
-- Fri Aug 12 22:38:42 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema task_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema task_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `task_manager` DEFAULT CHARACTER SET utf8 ;
USE `task_manager` ;

-- -----------------------------------------------------
-- Table `task_manager`.`tb_tarefas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_manager`.`tb_tarefas` (
  `id` INT NULL AUTO_INCREMENT,
  `tarefas` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `descricao` TEXT(80) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NULL,
  `prazo` DATE NULL,
  `prioridade` INT(1) NULL,
  `tarefa_concluida` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
